sudo: required

services:
  - docker

script:
  - docker-compose up -d
  - sleep 20
  - docker-compose run --rm app bin/console security:check
  - docker-compose run --rm app bin/console doctrine:schema:create
